/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/routes/__root'
import { Route as WelcomeRouteImport } from './app/routes/welcome'
import { Route as AuthRouteImport } from './app/routes/auth'
import { Route as MainRouteImport } from './app/routes/_main'
import { Route as MainIndexRouteImport } from './app/routes/_main/index'
import { Route as MainProblemListRouteImport } from './app/routes/_main/problemList'
import { Route as MainClientsRouteImport } from './app/routes/_main/clients'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)
const MainProblemListRoute = MainProblemListRouteImport.update({
  id: '/problemList',
  path: '/problemList',
  getParentRoute: () => MainRoute,
} as any)
const MainClientsRoute = MainClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => MainRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/auth': typeof AuthRoute
  '/welcome': typeof WelcomeRoute
  '/clients': typeof MainClientsRoute
  '/problemList': typeof MainProblemListRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/welcome': typeof WelcomeRoute
  '/clients': typeof MainClientsRoute
  '/problemList': typeof MainProblemListRoute
  '/': typeof MainIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteWithChildren
  '/auth': typeof AuthRoute
  '/welcome': typeof WelcomeRoute
  '/_main/clients': typeof MainClientsRoute
  '/_main/problemList': typeof MainProblemListRoute
  '/_main/': typeof MainIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/welcome' | '/clients' | '/problemList'
  fileRoutesByTo: FileRoutesByTo
  to: '/auth' | '/welcome' | '/clients' | '/problemList' | '/'
  id:
    | '__root__'
    | '/_main'
    | '/auth'
    | '/welcome'
    | '/_main/clients'
    | '/_main/problemList'
    | '/_main/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRoute: typeof MainRouteWithChildren
  AuthRoute: typeof AuthRoute
  WelcomeRoute: typeof WelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/problemList': {
      id: '/_main/problemList'
      path: '/problemList'
      fullPath: '/problemList'
      preLoaderRoute: typeof MainProblemListRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/clients': {
      id: '/_main/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof MainClientsRouteImport
      parentRoute: typeof MainRoute
    }
  }
}

interface MainRouteChildren {
  MainClientsRoute: typeof MainClientsRoute
  MainProblemListRoute: typeof MainProblemListRoute
  MainIndexRoute: typeof MainIndexRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainClientsRoute: MainClientsRoute,
  MainProblemListRoute: MainProblemListRoute,
  MainIndexRoute: MainIndexRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MainRoute: MainRouteWithChildren,
  AuthRoute: AuthRoute,
  WelcomeRoute: WelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
